### ISSUE TITLE
.setPropertyType() in Property.Builder does not work

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/thingweb#15]
Properties in the produced TD do not have `@type`s.

**Comment by danielpeintner** [comment]
The recent commit https://github.com/thingweb/thingweb/commit/61c383f990ce6c87cbd81314554e5f392e3bd73e should fix this issue.

Please confirm.

**Comment by mkovatsc** [comment]
Works, many thanks!

Let's go into the next round in a new issue ;)
