### ISSUE TITLE
thingweb-parser depends on exificient:0.9.6-SNAPSHOT which is not available

### ISSUE THREAD

**Issue by alfonsoros88** [thingweb/thingweb#7]
The 0.9.6a-SNAPSHOT version is not available and therefore the thingweb-parser can't be build. In repo1.maven.org is the exificient:0.9.6. A possible solution is then to remove the 'a-SNAPSHOT' from the build.gradle file.

Nevetheless, the tests fail to build afterwards.

**Comment by danielpeintner** [comment]
The gradle test run seems to work just fine, see https://drone.io/github.com/thingweb/thingweb/latest for latest tests.

We can now also change to the official exificient:0.9.6 release which was published some days ago if the issue doesn't go away...

**Comment by danielpeintner** [comment]
I changed the snapshot version of exificient-for-json to release, see https://github.com/thingweb/thingweb/commit/5afbe98919238f07f92988a06fed116f60753801.

Hope this resolves any pending issue. The drone build is still fine, https://drone.io/github.com/thingweb/thingweb/170

**Comment by danielpeintner** [comment]
Has the issue been resolved?

**Comment by alfonsoros88** [comment]
Yes, it builds fine now. Thanks :)
